### ISSUE TITLE
Link error building under MSYS2 on Windows

### ISSUE THREAD

**Issue by negativekelvin** [mruby-esp32/mruby-esp32#1] opened 2016-10-25 18:15 UTC
I'm getting the following error:

```
LD mruby_example.elf
C:/esp32/mruby-esp32/build/mruby_component\libmruby_component.a(backtrace.o):(.literal.print_backtrace+0x0): undefined reference to `_impure_ptr'
```

Probably some flags missing? Any tips?

**Comment by carsonmcdonald** [comment] 2016-10-25 18:28
@negativekelvin I had that same issue when the header files weren't getting added to the build environment correctly so I'm guessing that they aren't for you for some reason. This would be the line to look at: https://github.com/carsonmcdonald/mruby-esp32/blob/master/components/mruby_component/esp32_build_config.rb#L32  It may be that the environment variable is missing or potentially the format isn't getting split the same under MSYS2. Let me know if you run into a dead end and I can see if I can reproduce the issue on a VM.

**Comment by negativekelvin** [comment] 2016-10-25 19:43
The includes seem to be ok.  The objection appears to be with `FILE *stream = stderr;`

**Comment by negativekelvin** [comment] 2016-10-25 19:55
The includes seem to be ok

**Comment by negativekelvin** [comment] 2016-10-26 01:45
~~Well I figured out that error is with the host build and can get around it by adding the msys2/usr/include directory but then get stuck here:~~

~~`Don't know how to rake /home/esp32/mruby-esp32/components/mruby_component/mruby/src/array.c`~~

**Comment by carsonmcdonald** [comment] 2016-10-26 02:13
You may want to try the same thing in the host as what you will find in the esp32 build. I had to strip out the -MP flag because that causes .d files to contain phony entries that the mruby build system doesn't understand.

**Comment by negativekelvin** [comment] 2016-10-26 12:47
Well I was able to get it to build on Win10 and all I had to do was comment out `_exit` from mruby_main.c

Running `make`again requires either `make clean` in just the mruby directory or in the project directory or it will result in the `Don't know how to rake` error.

~~On Win7 I still get the `_impure_ptr` error.  All other things are equal besides OS, AFAIK.~~

**Comment by negativekelvin** [comment] 2016-10-29 07:11
`_impure_ptr` error resolved on Win7.  It was a configuration error within MSYS2 environment.

So the only issue is with rerunning make.

**Comment by yuuu** [comment] 2023-07-15 22:28
@negativekelvin 
Does this issue still occur on the latest main branch?
If not, may I close this issue ?

**Comment by yuuu** [comment] 2023-07-23 21:26
Closed as it is not expected to occur at this time.

**Closed as completed by yuuu** 2023-07-23 21:26 UTC
